server:
  port: 8081
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
  datasource:
    url: jdbc:h2:file:./target/db-name;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=TRUE
    # on memory
    # url: jdbc:h2:meme:test
    data-password: sa
    data-username:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level: debug